name: Mirror SDL2 upstream test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh
        
      - name: Clone SDL2 upstream (bare)
        run: |
          git clone --mirror https://github.com/libsdl-org/SDL.git sdl2.git

      - name: Push to org mirror
        run: |
          cd sdl2.git
          git push --mirror https://x-access-token:${{ secrets.MIRROR_PAT_TOKEN }}@github.com/org-foundation/mirrors-sdl2.git
